#!/usr/bin/env python3
"""
Headless LAM → FLAME web-format bake — one image in, one FLAME zip out (WITH TEETH).

Sibling of colab_bake_oac.py. Where the OAC runner produces the no-teeth OAC zip
(skin.glb + offset.ply + animation.glb + vertex_order.json, via the hardcoded
template_file.fbx that can't carry teeth), THIS runner produces LAM's **FLAME web
format** — the same 6-file set man.zip uses and the GaussianAvatarShow demo loads
with useFlame:true:

    <stem>/skin.glb, flame_params.json, lbs_weight_20k.json,
           bone_tree.json, offset.ply, vertex_order.json

Teeth work here because this path exports the GLB DIRECTLY from the model's own
FLAME mesh (no template_file.fbx injection, no fixed vertex count) — so enabling
cfg.model.add_teeth=True just makes every artifact bigger by the same subdivided-
teeth vertex count, consistently. (See tools/TEETH_AND_SPEECH.md.)

It mirrors core_fn's FLAME/h5 branch (app_lam.py lines 283-289), which is gated
behind a hardcoded global `h5_rendering=False` in the app — we bypass that and
call the four functions directly:
    1) flame_model.save_h5_info()  -> lbs_weight_20k.json, bone_tree.json,
                                       nature.obj, bs/expr0..99.obj
    2) cano_gs.save_ply()          -> offset.ply
    3) Blender generateGLBWithBlender_v2.py -> skin.glb + vertex_order.json
    4) assemble the zip            -> our renderer's folder+dir-entry convention
flame_params.json is NOT generated by LAM — it's the driving clip's params; we
copy it from the chosen --motion clip (we overwrite it live in the spike anyway,
so its content only needs valid keys/shapes).

Run from inside the cloned LAM repo (cwd = /content/LAM — the Blender script's
paths are hardcoded to ./runtime_data):
    python colab_bake_flame.py \
        --image assets/sample_input/fisherman.jpg \
        --blender_path /content/blender-4.0.2-linux-x64/blender \
        --motion Look_In_My_Eyes

⚠️ Mirrors LAM internals at a point in time (save_h5_info / generateGLBWithBlender_v2
/ create_zip_archive). If a signature drifts, this raises — fall back to enabling
the app's `h5_rendering=True` global and running LAM's own Gradio path.
"""
import argparse
import os
import sys

# Robustness (conda run doesn't reliably pass a shell-prefix env var or cwd to
# python): force the headless matplotlib backend BEFORE lam imports matplotlib,
# and put the repo on sys.path so `lam`/`tools` resolve regardless of cwd.
os.environ["MPLBACKEND"] = "Agg"
sys.path.insert(0, "/content/LAM")

import shutil
import zipfile
from glob import glob
from pathlib import Path


# Standard ARKit-52 blendshape order (matches LAM_Audio2Expression's ARKitBlendShape
# list / flame_arkit_bs column order). eyeBlinkLeft/Right are the dedicated lid
# channels that give a CLEAN blink — the whole point of the --arkit bake.
ARKIT_52 = [
    "browDownLeft", "browDownRight", "browInnerUp", "browOuterUpLeft", "browOuterUpRight",
    "cheekPuff", "cheekSquintLeft", "cheekSquintRight", "eyeBlinkLeft", "eyeBlinkRight",
    "eyeLookDownLeft", "eyeLookDownRight", "eyeLookInLeft", "eyeLookInRight",
    "eyeLookOutLeft", "eyeLookOutRight", "eyeLookUpLeft", "eyeLookUpRight",
    "eyeSquintLeft", "eyeSquintRight", "eyeWideLeft", "eyeWideRight", "jawForward",
    "jawLeft", "jawOpen", "jawRight", "mouthClose", "mouthDimpleLeft", "mouthDimpleRight",
    "mouthFrownLeft", "mouthFrownRight", "mouthFunnel", "mouthLeft", "mouthLowerDownLeft",
    "mouthLowerDownRight", "mouthPressLeft", "mouthPressRight", "mouthPucker", "mouthRight",
    "mouthRollLower", "mouthRollUpper", "mouthShrugLower", "mouthShrugUpper",
    "mouthSmileLeft", "mouthSmileRight", "mouthStretchLeft", "mouthStretchRight",
    "mouthUpperUpLeft", "mouthUpperUpRight", "noseSneerLeft", "noseSneerRight", "tongueOut",
]


def bake_arkit_h5(flame_model, shape_param, fd: str) -> int:
    """EXPERIMENTAL — bake the FLAME/teeth head with the 52 ARKit blendshapes
    (named morphs incl. eyeBlinkLeft/Right) INSTEAD of the 100 expr PCA. Mirrors
    FlameHeadSubdivided.save_h5_info but loops the ARKit basis and names each
    bs/<arkitName>.obj, so the GLB (Blender names shape keys by filename) carries
    ARKit morph targetNames → the renderer + our ARKit driver drive blink/emotion
    BY NAME, with a dedicated (clean) blink. See tools/TEETH_AND_SPEECH.md §5.

    Requires the model to be LAM's ARKit FLAME head (flame_arkit.py): its
    shapedirs_up must carry the 52 ARKit dirs after the shape dirs. Fails loud if
    the basis isn't ARKit-shaped. lbs_weight/bone_tree/nature are basis-independent.
    """
    import json
    import torch
    import trimesh
    from lam.models.rendering.flame_model.flame import blend_shapes

    os.makedirs(os.path.join(fd, "bs"), exist_ok=True)
    m = flame_model
    n_shape = m.n_shape_params
    n_expr = m.shapedirs_up.shape[-1] - n_shape
    assert n_expr == 52, (
        f"--arkit needs the ARKit FLAME basis (52 dirs), got {n_expr}. The model is "
        f"the PCA head — build LAM's flame_arkit.py FlameHeadSubdivided (expr_params=52, "
        f"flame_arkit_bs.npy) for the renderer's flame_model. See TEETH_AND_SPEECH.md §5."
    )
    faces = m.faces_up.cpu().numpy()
    B = shape_param.shape[0]
    v_template = m.v_template_up.unsqueeze(0).expand(B, -1, -1)
    v_shaped = v_template + blend_shapes(shape_param, m.shapedirs_up[:, :, :n_shape])

    with open(os.path.join(fd, "lbs_weight_20k.json"), "w") as of:
        json.dump(m.lbs_weights_up.cpu().numpy().tolist(), of)
    v_ori = m.v_template.unsqueeze(0).expand(B, -1, -1) + blend_shapes(shape_param, m.shapedirs[:, :, :n_shape])
    m.save_bone_tree(v_ori, os.path.join(fd, "bone_tree.json"))
    trimesh.Trimesh(vertices=v_shaped.squeeze(0).cpu().numpy(), faces=faces).export(os.path.join(fd, "nature.obj"))

    for i, name in enumerate(ARKIT_52):
        e = torch.zeros((1, 52), device=v_shaped.device); e[:, i] = 1.0
        v_e = v_shaped + blend_shapes(e, m.shapedirs_up[:, :, n_shape:])
        trimesh.Trimesh(vertices=v_e.squeeze(0).cpu().numpy(), faces=faces).export(os.path.join(fd, "bs", f"{name}.obj"))
    print(f"[arkit] baked 52 ARKit blendshape morphs (bs/<name>.obj), incl. eyeBlinkLeft/Right")
    return 0


def build_arkit_flame_model(cfg, add_teeth: bool):
    """EXPERIMENTAL — build LAM's ARKit FLAME head (subdivided, teeth) for baking.
    Mirrors how GS3DRenderer builds the PCA FlameHeadSubdivided, but from
    flame_arkit.py with expr_params=52. The exact class/args may differ across LAM
    revisions — adjust here if it raises. Returns the model on cuda."""
    from lam.models.rendering.flame_model import flame_arkit
    Cls = getattr(flame_arkit, "FlameHeadSubdivided", None) or getattr(flame_arkit, "FlameHead")
    human_model_path = getattr(cfg.model, "human_model_path", "./model_zoo/human_model_files")
    sub = getattr(cfg.model, "flame_subdivide_num", 1)
    model = Cls(
        300, 52, add_teeth=add_teeth, add_shoulder=False,
        flame_model_path=f"{human_model_path}/flame_assets/flame/flame2023.pkl",
        subdivide_num=sub,
    )
    return model.cuda().eval()


def find_motion(motion_arg: str) -> str:
    """Pick a driving motion-sequence dir (provides flame shape + render params)."""
    if motion_arg and motion_arg != "auto":
        d = f"./assets/sample_motion/export/{motion_arg}"
        assert os.path.isdir(d), f"motion not found: {d}"
        return d
    cands = sorted(glob("./assets/sample_motion/export/*/"))
    assert cands, "no sample motions under assets/sample_motion/export/ — did the assets download succeed?"
    for c in cands:
        if "Look_In_My_Eyes" in c:
            return c.rstrip("/")
    return cands[0].rstrip("/")


def find_flame_params_json(clip_dir: str, override: str) -> str:
    """The 6th file isn't generated by LAM — it's the driving clip's flame_params.json.
    We overwrite it live in the spike, so its content only needs valid keys/shapes."""
    if override.strip():
        assert os.path.exists(override), f"--flame-params not found: {override}"
        return override
    # create_zip_archive reads <clip>/flame_params.json; some layouts nest it.
    cands = [
        os.path.join(clip_dir, "flame_params.json"),
        os.path.join(clip_dir, "flame_param", "flame_params.json"),
    ]
    for c in cands:
        if os.path.exists(c):
            return c
    hits = glob(os.path.join(clip_dir, "**", "flame_params.json"), recursive=True)
    assert hits, (
        f"no flame_params.json under {clip_dir}. Pass one with --flame-params "
        f"(keys: translation, rotation, neck_pose, jaw_pose, eyes_pose, shape, expr)."
    )
    return hits[0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, help="input portrait, e.g. assets/sample_input/fisherman.jpg")
    ap.add_argument("--blender_path", required=True, help="path to Blender >=4.0 executable")
    ap.add_argument("--motion", default="auto", help="driving clip under assets/sample_motion/export, or 'auto'")
    ap.add_argument("--flame-params", dest="flame_params", default="",
                    help="override path to flame_params.json (else taken from the --motion clip)")
    ap.add_argument("--arkit", dest="arkit", action="store_true",
                    help="EXPERIMENTAL: bake the teeth head with LAM's 52 ARKit blendshapes "
                         "(named morphs incl. eyeBlinkLeft/Right) instead of the 100 expr PCA → "
                         "teeth + a CLEAN dedicated blink, driven by name by our ARKit driver. "
                         "Needs LAM's flame_arkit.py + flame_arkit_bs.npy; validate on Colab. "
                         "See tools/TEETH_AND_SPEECH.md §5.")
    ap.add_argument("--no-teeth", dest="no_teeth", action="store_true",
                    help="bake WITHOUT teeth (default is WITH teeth — the whole point of this path). "
                         "Teeth flow cleanly here: no template_file.fbx, GLB exported from the model's FLAME mesh.")
    ap.add_argument("--tag", default="",
                    help="suffix for the output name so variants don't collide, e.g. --tag teeth -> "
                         "<image>_teeth.zip (distinct zip + inner folder + switcher chip).")
    args = ap.parse_args()

    add_teeth = not args.no_teeth
    assert os.path.exists(args.image), f"image not found: {args.image}"
    assert os.path.exists(args.blender_path), f"blender not found: {args.blender_path}"
    blender_script = "tools/generateGLBWithBlender_v2.py"
    assert os.path.exists(blender_script), (
        f"missing {blender_script} — this LAM checkout doesn't have the FLAME GLB exporter; "
        f"update LAM or use the OAC runner."
    )

    # --- env + config, copied from app_lam.launch_gradio_app -----------------
    os.environ.update({
        "APP_ENABLED": "1",
        "APP_MODEL_NAME": "./model_zoo/lam_models/releases/lam/lam-20k/step_045500/",
        "APP_INFER": "./configs/inference/lam-20k-8gpu.yaml",
        "APP_TYPE": "infer.lam",
        "NUMBA_THREADING_LAYER": "omp",
    })

    import matplotlib
    matplotlib.use("Agg")  # belt-and-suspenders with MPLBACKEND set at module top
    import torch
    import app_lam  # importing does NOT launch gradio (that's under __main__)
    from lam.runners.infer.head_utils import prepare_motion_seqs, preprocess_image

    # parse_configs reads --blender_path off sys.argv; hand it a clean argv.
    sys.argv = ["colab_bake_flame.py", "--blender_path", args.blender_path]
    cfg, _ = app_lam.parse_configs()

    # TEETH: flip the config flag BEFORE building the model. Flows
    # ModelLAM.__init__ -> GS3DRenderer -> FlameHeadSubdivided(add_teeth=...). The
    # shipped configs/inference/lam-20k-8gpu.yaml has add_teeth:false. Unlike OAC,
    # this is the ONLY toggle needed — every exported artifact derives from the
    # same FlameHeadSubdivided tensors, so teeth stay consistent (no FBX desync).
    cfg.model.add_teeth = add_teeth
    print(f"cfg.model.add_teeth = {add_teeth} ({'TEETH' if add_teeth else 'no teeth'})")

    print("building model + flame tracking…")
    lam = app_lam._build_model(cfg)
    lam.to("cuda").eval()

    from tools.flame_tracking_single_image import FlameTrackingSingleImage
    flametracking = FlameTrackingSingleImage(
        output_dir="output/tracking",
        alignment_model_path="./model_zoo/flame_tracking_models/68_keypoints_model.pkl",
        vgghead_model_path="./model_zoo/flame_tracking_models/vgghead/vgg_heads_l.trcd",
        human_matting_path="./model_zoo/flame_tracking_models/matting/stylematte_synth.pt",
        facebox_model_path="./model_zoo/flame_tracking_models/FaceBoxesV2.pth",
        detect_iris_landmarks=False,
    )

    clip_dir = find_motion(args.motion)
    motion_seqs_dir = os.path.join(clip_dir, "flame_param")
    assert os.path.isdir(motion_seqs_dir), f"missing flame_param dir: {motion_seqs_dir}"
    flame_params_src = find_flame_params_json(clip_dir, args.flame_params)
    base_iid = os.path.basename(args.image).split(".")[0]
    if args.tag.strip():
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in args.tag.strip())
        base_iid = f"{base_iid}_{safe}"
    print(f"image={args.image}  iid={base_iid}  clip={clip_dir}")
    print(f"flame_params.json (driving clip; overwritten live in spike): {flame_params_src}")

    # --- flame tracking on the input image (identical to OAC runner) ----------
    tmp_dir = "output/_bake_tmp"
    os.makedirs(tmp_dir, exist_ok=True)
    image_raw = os.path.join(tmp_dir, "raw.png")
    from PIL import Image
    with Image.open(args.image).convert("RGB") as im:
        im.save(image_raw)

    assert flametracking.preprocess(image_raw) == 0, "flametracking preprocess failed"
    assert flametracking.optimize() == 0, "flametracking optimize failed"
    rc, output_dir = flametracking.export()
    assert rc == 0, "flametracking export failed"

    image_path = os.path.join(output_dir, "images/00000_00.png")
    mask_path = os.path.join(output_dir, "fg_masks/00000_00.png")

    aspect_standard = 1.0 / 1.0
    image, _, _, shape_param = preprocess_image(
        image_path, mask_path=mask_path, intr=None, pad_ratio=0, bg_color=1.0,
        max_tgt_size=None, aspect_standard=aspect_standard, enlarge_ratio=[1.0, 1.0],
        render_tgt_size=cfg.source_size, multiply=14, need_mask=True, get_shape_param=True,
    )

    src = image_path.split("/")[-3]
    driven = motion_seqs_dir.split("/")[-2]
    motion_seq = prepare_motion_seqs(
        motion_seqs_dir, None, save_root=tmp_dir, fps=30, bg_color=1.0,
        aspect_standard=aspect_standard, enlarge_ratio=[1.0, 1, 0],
        render_image_res=cfg.render_size, multiply=16, need_mask=False,
        vis_motion=False, shape_param=shape_param, test_sample=False,
        cross_id=False, src_driven=[src, driven],
    )

    # --- inference → canonical gaussians (identical to OAC runner) ------------
    device, dtype = "cuda", torch.float32
    motion_seq["flame_params"]["betas"] = shape_param.unsqueeze(0)
    print("running LAM inference…")
    with torch.no_grad():
        res = lam.infer_single_view(
            image.unsqueeze(0).to(device, dtype), None, None,
            render_c2ws=motion_seq["render_c2ws"].to(device),
            render_intrs=motion_seq["render_intrs"].to(device),
            render_bg_colors=motion_seq["render_bg_colors"].to(device),
            flame_params={k: v.to(device) for k, v in motion_seq["flame_params"].items()},
        )

    # === FLAME / h5 export (core_fn lines 283-289, sans the h5_rendering gate) ===
    # The Blender script's paths are HARDCODED to ./runtime_data — so we stage
    # there (cwd must be the LAM repo root), then assemble the final zip from it.
    h5_fd = "./runtime_data"
    if os.path.isdir(h5_fd):
        shutil.rmtree(h5_fd)  # avoid stale files from a previous bake
    os.makedirs(os.path.join(h5_fd, "bs"), exist_ok=True)

    if args.arkit:
        print("⚠️  --arkit (EXPERIMENTAL): baking 52 ARKit blendshapes (clean blink) instead of PCA…")
        arkit_model = build_arkit_flame_model(cfg, add_teeth)
        bake_arkit_h5(arkit_model, shape_param.unsqueeze(0).cuda(), fd=h5_fd)
    else:
        print("save_h5_info → lbs_weight_20k.json, bone_tree.json, nature.obj, bs/expr0..99.obj …")
        lam.renderer.flame_model.save_h5_info(shape_param.unsqueeze(0).cuda(), fd=h5_fd)

    print("save_ply → offset.ply …")
    res["cano_gs_lst"][0].save_ply(os.path.join(h5_fd, "offset.ply"), rgb2sh=False, offset2xyz=True)

    # teeth diagnostic: nature.obj vertex count (informational; this path doesn't desync)
    try:
        nverts = sum(1 for ln in open(os.path.join(h5_fd, "nature.obj")) if ln.startswith("v "))
        nbs = len(glob(os.path.join(h5_fd, "bs", "*.obj")))
        basis = "ARKit-52" if args.arkit else "expr-PCA"
        print(f"[flame] nature.obj verts={nverts}  blendshapes={nbs} ({basis})  teeth={'ON' if add_teeth else 'off'}")
    except Exception as e:
        print(f"[flame] count diagnostic skipped: {e}")

    print("Blender generateGLBWithBlender_v2.py → skin.glb + vertex_order.json …")
    rc = os.system(f'"{args.blender_path}" --background --python {blender_script}')
    assert rc == 0, f"Blender GLB export failed (exit {rc}). Check Blender>=4.0 and runtime_data/ inputs."
    for f in ("skin.glb", "vertex_order.json"):
        p = os.path.join(h5_fd, f)
        assert os.path.exists(p), f"Blender step did not produce {p}"

    # --- assemble OUR zip: inner folder == zip-name, WITH a directory entry ----
    # (create_zip_archive uses arcname h5_render_data/ and NO dir entry; our
    #  renderer discovers the folder via a DIRECTORY ENTRY or throws 'file fold is
    #  not found' — so we write the zip ourselves, like the OAC runner.)
    out_dir = "./output/flame_render"
    os.makedirs(out_dir, exist_ok=True)
    members = {
        "skin.glb": os.path.join(h5_fd, "skin.glb"),
        "flame_params.json": flame_params_src,
        "lbs_weight_20k.json": os.path.join(h5_fd, "lbs_weight_20k.json"),
        "bone_tree.json": os.path.join(h5_fd, "bone_tree.json"),
        "offset.ply": os.path.join(h5_fd, "offset.ply"),
        "vertex_order.json": os.path.join(h5_fd, "vertex_order.json"),
    }
    missing = [k for k, v in members.items() if not os.path.exists(v)]
    assert not missing, f"FLAME export incomplete, missing: {missing}"

    out_zip = os.path.join(out_dir, base_iid + ".zip")
    if os.path.exists(out_zip):
        os.remove(out_zip)
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
        di = zipfile.ZipInfo(base_iid + "/")
        di.external_attr = (0o40755 << 16) | 0x10  # unix dir bit + MS-DOS dir flag
        z.writestr(di, b"")
        for arcname, srcpath in members.items():
            z.write(srcpath, arcname=os.path.join(base_iid, arcname))

    print("\n✅ FLAME zip ready:", os.path.abspath(out_zip))
    print("   inner folder:", base_iid, "(with directory entry)")
    print("   contents:", ", ".join(members.keys()))
    print("   load it in the FLAME spike:  /flame-spike.html?avatar=<url to this zip>")
    print("   or compare v1 vs v2:         /compare.html?v1=<oac>&v2=<this flame zip>")


if __name__ == "__main__":
    main()
