#!/usr/bin/env python3
"""
Headless LAM → FLAME web-format bake — one image in, one FLAME zip out (WITH TEETH).

Sibling of colab_bake_oac.py. Where the OAC runner produces the no-teeth OAC zip
(skin.glb + offset.ply + animation.glb + vertex_order.json, via the hardcoded
template_file.fbx that can't carry teeth), THIS runner produces LAM's **FLAME web
format** — the same 6-file set man.zip uses and the GaussianAvatarShow demo loads
with useFlame:true:

    <stem>/skin.glb, flame_params.json, lbs_weight_20k.json,
           bone_tree.json, offset.ply, vertex_order.json

Teeth work here because this path exports the GLB DIRECTLY from the model's own
FLAME mesh (no template_file.fbx injection, no fixed vertex count) — so enabling
cfg.model.add_teeth=True just makes every artifact bigger by the same subdivided-
teeth vertex count, consistently. (See tools/TEETH_AND_SPEECH.md.)

It mirrors core_fn's FLAME/h5 branch (app_lam.py lines 283-289), which is gated
behind a hardcoded global `h5_rendering=False` in the app — we bypass that and
call the four functions directly:
    1) flame_model.save_h5_info()  -> lbs_weight_20k.json, bone_tree.json,
                                       nature.obj, bs/expr0..99.obj
    2) cano_gs.save_ply()          -> offset.ply
    3) Blender generateGLBWithBlender_v2.py -> skin.glb + vertex_order.json
    4) assemble the zip            -> our renderer's folder+dir-entry convention
flame_params.json is NOT generated by LAM — it's the driving clip's params; we
copy it from the chosen --motion clip (we overwrite it live in the spike anyway,
so its content only needs valid keys/shapes).

Run from inside the cloned LAM repo (cwd = /content/LAM — the Blender script's
paths are hardcoded to ./runtime_data):
    python colab_bake_flame.py \
        --image assets/sample_input/fisherman.jpg \
        --blender_path /content/blender-4.0.2-linux-x64/blender \
        --motion Look_In_My_Eyes

⚠️ Mirrors LAM internals at a point in time (save_h5_info / generateGLBWithBlender_v2
/ create_zip_archive). If a signature drifts, this raises — fall back to enabling
the app's `h5_rendering=True` global and running LAM's own Gradio path.
"""
import argparse
import os
import sys

# Robustness (conda run doesn't reliably pass a shell-prefix env var or cwd to
# python): force the headless matplotlib backend BEFORE lam imports matplotlib,
# and put the repo on sys.path so `lam`/`tools` resolve regardless of cwd.
os.environ["MPLBACKEND"] = "Agg"
sys.path.insert(0, "/content/LAM")

import shutil
import zipfile
from glob import glob
from pathlib import Path


# Standard ARKit-52 blendshape order (matches LAM_Audio2Expression's ARKitBlendShape
# list / flame_arkit_bs column order). eyeBlinkLeft/Right are the dedicated lid
# channels that give a CLEAN blink — the whole point of the --arkit bake.
ARKIT_52 = [
    "browDownLeft", "browDownRight", "browInnerUp", "browOuterUpLeft", "browOuterUpRight",
    "cheekPuff", "cheekSquintLeft", "cheekSquintRight", "eyeBlinkLeft", "eyeBlinkRight",
    "eyeLookDownLeft", "eyeLookDownRight", "eyeLookInLeft", "eyeLookInRight",
    "eyeLookOutLeft", "eyeLookOutRight", "eyeLookUpLeft", "eyeLookUpRight",
    "eyeSquintLeft", "eyeSquintRight", "eyeWideLeft", "eyeWideRight", "jawForward",
    "jawLeft", "jawOpen", "jawRight", "mouthClose", "mouthDimpleLeft", "mouthDimpleRight",
    "mouthFrownLeft", "mouthFrownRight", "mouthFunnel", "mouthLeft", "mouthLowerDownLeft",
    "mouthLowerDownRight", "mouthPressLeft", "mouthPressRight", "mouthPucker", "mouthRight",
    "mouthRollLower", "mouthRollUpper", "mouthShrugLower", "mouthShrugUpper",
    "mouthSmileLeft", "mouthSmileRight", "mouthStretchLeft", "mouthStretchRight",
    "mouthUpperUpLeft", "mouthUpperUpRight", "noseSneerLeft", "noseSneerRight", "tongueOut",
]


# Custom IDENTITY-correction blendshapes (not ARKit — ARKit is expression-only).
# Procedural vertex displacements over the lip/chin region so the live panel can
# sculpt the baked neutral (lip fullness/width, chin point) the FLAME shape can't.
# EXPERIMENTAL — regions are anchored to eye/jaw positions from bone_tree.json and
# scaled by eye-separation (robust across heads), with smooth Gaussian weights (no
# seams). Signed -1..1 in the panel (e.g. lipFullness negative = thinner). Tune the
# AMP/offset constants below if a morph grabs the wrong area (counts are printed).
CUSTOM_SHAPE_MORPHS = True  # set False to bake ARKit-only

def bake_custom_shape_morphs(v_np, faces, fd: str) -> list:
    import json
    import numpy as np
    import trimesh

    # anchors from bone_tree.json (eyes + jaw), written by save_h5_info
    bt = json.load(open(os.path.join(fd, "bone_tree.json")))
    def find(node, name):
        if node.get("name") == name: return node["position"]
        for c in node.get("children", []):
            r = find(c, name)
            if r: return r
        return None
    root = bt["bones"][0]
    le, re_, jaw = find(root, "leftEye"), find(root, "rightEye"), find(root, "jaw")
    eyeY = (le[1] + re_[1]) / 2.0
    faceScale = max(1e-4, abs(le[0] - re_[0]))           # eye separation ≈ face width unit
    cx = (le[0] + re_[0]) / 2.0

    mesh = trimesh.Trimesh(vertices=v_np, faces=faces, process=False)
    Nrm = np.asarray(mesh.vertex_normals)
    x, y, z = v_np[:, 0], v_np[:, 1], v_np[:, 2]

    mouthY = eyeY - 1.3 * faceScale                      # mouth ≈ 1.3 eye-seps below eyes
    chinY = eyeY - 2.2 * faceScale
    # front z near the mouth band (lips protrude): max z of central, mouth-height verts
    band = (np.abs(y - mouthY) < 0.5 * faceScale) & (np.abs(x - cx) < faceScale) & (z > 0)
    frontZ = float(np.percentile(z[band], 90)) if band.any() else float(z.max())

    def gauss(cxx, cyy, czz, rx, ry, rz):
        return np.exp(-(((x - cxx) / rx) ** 2 + ((y - cyy) / ry) ** 2 + ((z - czz) / rz) ** 2))
    w_lip = gauss(cx, mouthY, frontZ, 0.95 * faceScale, 0.38 * faceScale, 0.95 * faceScale)
    w_chin = gauss(cx, chinY, frontZ, 1.05 * faceScale, 0.6 * faceScale, 1.05 * faceScale)
    upper = (y >= mouthY).astype(np.float32)
    lower = (y < mouthY).astype(np.float32)

    AMP = 0.12 * faceScale                               # full-slider displacement, scales with head
    defs = {
        "lipFullness": v_np + Nrm * (AMP * w_lip)[:, None],
        "upperLipFull": v_np + Nrm * (AMP * w_lip * upper)[:, None],
        "lowerLipFull": v_np + Nrm * (AMP * w_lip * lower)[:, None],
        "lipWiden": v_np + np.stack([np.sign(x - cx) * AMP * w_lip, np.zeros_like(y), np.zeros_like(z)], 1),
        "chinSoften": v_np + np.stack([np.zeros_like(x), 0.6 * AMP * w_chin, -AMP * w_chin], 1),
    }
    bs_dir = os.path.join(fd, "bs")
    for name, vd in defs.items():
        trimesh.Trimesh(vertices=vd, faces=faces, process=False).export(os.path.join(bs_dir, f"{name}.obj"))
    print(f"[custom] eyeY={eyeY:.4f} faceScale={faceScale:.4f} mouthY={mouthY:.4f} chinY={chinY:.4f} frontZ={frontZ:.4f}")
    print(f"[custom] lip verts(w>.5)={int((w_lip>0.5).sum())} chin verts(w>.5)={int((w_chin>0.5).sum())}")
    print(f"[custom] wrote {len(defs)} identity-sculpt morphs: {', '.join(defs)}")
    return list(defs)


def write_arkit_morphs(arkit_model, shape_param, faces, fd: str) -> int:
    """EXPERIMENTAL — replace the PCA expr morphs with the 52 ARKit blendshape
    morphs (named bs/<arkitName>.obj incl. eyeBlinkLeft/Right), so the GLB carries
    ARKit morph targetNames → our ARKit driver drives blink/emotion BY NAME with a
    dedicated (clean) blink. See tools/TEETH_AND_SPEECH.md §5.

    lbs_weight/bone_tree/nature/offset are written by the normal PCA save_h5_info
    (identity geometry is basis-independent — same v_template_up/faces/skinning);
    ONLY the morph blendshapes change. `faces` is the PCA model's faces_up (same
    topology). The ARKit model supplies v_template_up + shapedirs_up (300 shape +
    52 ARKit). The base v_shaped here MUST match nature.obj (it does: same
    v_template_up + same first-300 shape dirs).
    """
    import glob as _glob
    import torch
    import trimesh
    from lam.models.rendering.flame_model.flame import blend_shapes

    m = arkit_model
    n_shape = m.n_shape_params
    n_expr = m.shapedirs_up.shape[-1] - n_shape
    assert n_expr == 52, (
        f"--arkit expected a 52-dim ARKit basis, got {n_expr}. flame_arkit_bs.npy "
        f"didn't load as 52 blendshapes — check the asset."
    )
    bs_dir = os.path.join(fd, "bs")
    for f in _glob.glob(os.path.join(bs_dir, "expr*.obj")):
        os.remove(f)  # drop the PCA morphs written by save_h5_info

    B = shape_param.shape[0]
    v_shaped = m.v_template_up.unsqueeze(0).expand(B, -1, -1) + blend_shapes(shape_param, m.shapedirs_up[:, :, :n_shape])
    for i, name in enumerate(ARKIT_52):
        e = torch.zeros((1, 52), device=v_shaped.device); e[:, i] = 1.0
        v_e = v_shaped + blend_shapes(e, m.shapedirs_up[:, :, n_shape:])
        trimesh.Trimesh(vertices=v_e.squeeze(0).cpu().numpy(), faces=faces).export(os.path.join(bs_dir, f"{name}.obj"))
    print(f"[arkit] wrote 52 ARKit blendshape morphs (bs/<name>.obj), incl. eyeBlinkLeft/Right")
    if CUSTOM_SHAPE_MORPHS:
        try:
            bake_custom_shape_morphs(v_shaped.squeeze(0).cpu().numpy(), faces, fd)
        except Exception as e:
            print(f"[custom] WARNING: identity-sculpt morphs skipped ({e}) — ARKit-only head")
    return 0


def find_arkit_bs(human_model_path: str, override: str) -> str:
    """Locate the ARKit→FLAME blendshape basis .npy (the 52 ARKit dirs on FLAME
    topology). flame_arkit.py requires it (asserts existence) but NO config ships a
    default path, and it's not in the LAM repo — A2E 'manually customized' it. Try
    an override, then glob the asset tree, then fail with clear guidance."""
    if override.strip():
        assert os.path.exists(override), f"--arkit-bs not found: {override}"
        return override
    pats = ["*arkit*.npy", "*arkit*bs*.npy", "*flame_arkit*.npy"]
    roots = [human_model_path, "./model_zoo", "."]
    hits = []
    for r in roots:
        for p in pats:
            hits += glob(os.path.join(r, "**", p), recursive=True)
    hits = sorted(set(h for h in hits if os.path.exists(h)))
    assert hits, (
        "flame_arkit_bs .npy NOT FOUND. flame_arkit.py needs the ARKit→FLAME blendshape\n"
        "basis, but no LAM config ships it and it isn't in the repo (A2E manually\n"
        "customized it). It may not be in the public asset bundle. Options:\n"
        "  • pass --arkit-bs /path/to/flame_arkit_bs.npy if you have it, or\n"
        "  • check the LAM/A2E asset downloads, or request the asset from aigc3d.\n"
        f"Searched (recursive) under: {roots}"
    )
    print(f"[arkit] found ARKit basis candidate(s): {hits}; using {hits[0]}")
    return hits[0]


def _patch_flame_arkit_assert():
    """flame_arkit.py has an INVERTED assert: `assert expr_params != 52` (line ~108)
    with message 'must be equal to 52'. But the shapedirs reshape (line ~717) needs
    n_expr_params == 52 (shapedirs = 300 shape + 52 ARKit = 352). So the class only
    works with expr_params == 52, which the assert blocks. We flip that one assert in
    the source (idempotent) and reload the module. Returns the (reloaded) module."""
    import importlib
    from lam.models.rendering.flame_model import flame_arkit as fa
    src = fa.__file__
    txt = open(src, encoding="utf-8").read()
    if "assert expr_params != 52" in txt:
        txt = txt.replace("assert expr_params != 52", "assert expr_params == 52")
        open(src, "w", encoding="utf-8").write(txt)
        importlib.reload(fa)
        print(f"[arkit] patched inverted assert in {src} (!= 52 → == 52) and reloaded")
    return fa


def build_arkit_flame_model(cfg, add_teeth: bool, arkit_bs_override: str):
    """EXPERIMENTAL — build LAM's ARKit FLAME head (subdivided, teeth) for baking
    the 52 ARKit morphs. The class needs expr_params == 52 (the 52 ARKit dims come
    from flame_arkit_bs.npy and the subdivision reshape uses n_shape+n_expr=352), but
    ships an inverted assert that rejects 52 — we patch that first."""
    flame_arkit = _patch_flame_arkit_assert()
    Cls = getattr(flame_arkit, "FlameHeadSubdivided")
    hmp = getattr(cfg.model, "human_model_path", "./model_zoo/human_parametric_models")
    fa = f"{hmp}/flame_assets/flame"
    sub = getattr(cfg.model, "flame_subdivide_num", 1)
    bs = find_arkit_bs(hmp, arkit_bs_override)
    model = Cls(
        300, 52,                       # expr_params=52 (ARKit; reshape needs 300+52=352)
        flame_model_path=f"{fa}/flame2023.pkl",
        flame_lmk_embedding_path=f"{fa}/landmark_embedding_with_eyes.npy",
        flame_template_mesh_path=f"{fa}/head_template_mesh.obj",
        flame_parts_path=f"{fa}/FLAME_masks.pkl",
        add_teeth=add_teeth, add_shoulder=False,
        subdivide_num=sub,
        flame_arkit_bs_path=bs,
    )
    print(f"[arkit] built ARKit FLAME head (expr_params=52, teeth={add_teeth}, subdiv={sub})")
    return model.cuda().eval()


def find_motion(motion_arg: str) -> str:
    """Pick a driving motion-sequence dir (provides flame shape + render params)."""
    if motion_arg and motion_arg != "auto":
        d = f"./assets/sample_motion/export/{motion_arg}"
        assert os.path.isdir(d), f"motion not found: {d}"
        return d
    cands = sorted(glob("./assets/sample_motion/export/*/"))
    assert cands, "no sample motions under assets/sample_motion/export/ — did the assets download succeed?"
    for c in cands:
        if "Look_In_My_Eyes" in c:
            return c.rstrip("/")
    return cands[0].rstrip("/")


def find_flame_params_json(clip_dir: str, override: str) -> str:
    """The 6th file isn't generated by LAM — it's the driving clip's flame_params.json.
    We overwrite it live in the spike, so its content only needs valid keys/shapes."""
    if override.strip():
        assert os.path.exists(override), f"--flame-params not found: {override}"
        return override
    # create_zip_archive reads <clip>/flame_params.json; some layouts nest it.
    cands = [
        os.path.join(clip_dir, "flame_params.json"),
        os.path.join(clip_dir, "flame_param", "flame_params.json"),
    ]
    for c in cands:
        if os.path.exists(c):
            return c
    hits = glob(os.path.join(clip_dir, "**", "flame_params.json"), recursive=True)
    assert hits, (
        f"no flame_params.json under {clip_dir}. Pass one with --flame-params "
        f"(keys: translation, rotation, neck_pose, jaw_pose, eyes_pose, shape, expr)."
    )
    return hits[0]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", required=True, help="input portrait, e.g. assets/sample_input/fisherman.jpg")
    ap.add_argument("--blender_path", required=True, help="path to Blender >=4.0 executable")
    ap.add_argument("--motion", default="auto", help="driving clip under assets/sample_motion/export, or 'auto'")
    ap.add_argument("--flame-params", dest="flame_params", default="",
                    help="override path to flame_params.json (else taken from the --motion clip)")
    ap.add_argument("--arkit", dest="arkit", action="store_true",
                    help="EXPERIMENTAL: bake the teeth head with LAM's 52 ARKit blendshapes "
                         "(named morphs incl. eyeBlinkLeft/Right) instead of the 100 expr PCA → "
                         "teeth + a CLEAN dedicated blink, driven by name by our ARKit driver. "
                         "Needs LAM's flame_arkit.py + flame_arkit_bs.npy; validate on Colab. "
                         "See tools/TEETH_AND_SPEECH.md §5.")
    ap.add_argument("--arkit-bs", dest="arkit_bs", default="",
                    help="path to the ARKit→FLAME blendshape basis .npy (flame_arkit_bs). "
                         "If omitted, --arkit auto-discovers it under model_zoo; pass explicitly "
                         "if it lives elsewhere.")
    ap.add_argument("--no-teeth", dest="no_teeth", action="store_true",
                    help="bake WITHOUT teeth (default is WITH teeth — the whole point of this path). "
                         "Teeth flow cleanly here: no template_file.fbx, GLB exported from the model's FLAME mesh.")
    ap.add_argument("--shape-edit", dest="shape_edit", default="",
                    help="warp FLAME shape dims as deltas on the fitted shape, e.g. "
                         "'0:+1.5,3:-1.0'. Abstract FLAME PCA dims (not nose/jaw). "
                         "Same edit must be reused to reproduce a variant; bake several "
                         "to compare in the spike's variant switcher. Applied before "
                         "inference AND save_h5_info/ARKit-morph export so gaussians and "
                         "the FLAME mesh share one shape (else they desync).")
    ap.add_argument("--tag", default="",
                    help="suffix for the output name so variants don't collide, e.g. --tag teeth -> "
                         "<image>_teeth.zip (distinct zip + inner folder + switcher chip).")
    args = ap.parse_args()

    add_teeth = not args.no_teeth
    assert os.path.exists(args.image), f"image not found: {args.image}"
    assert os.path.exists(args.blender_path), f"blender not found: {args.blender_path}"
    blender_script = "tools/generateGLBWithBlender_v2.py"
    assert os.path.exists(blender_script), (
        f"missing {blender_script} — this LAM checkout doesn't have the FLAME GLB exporter; "
        f"update LAM or use the OAC runner."
    )

    # --- env + config, copied from app_lam.launch_gradio_app -----------------
    os.environ.update({
        "APP_ENABLED": "1",
        "APP_MODEL_NAME": "./model_zoo/lam_models/releases/lam/lam-20k/step_045500/",
        "APP_INFER": "./configs/inference/lam-20k-8gpu.yaml",
        "APP_TYPE": "infer.lam",
        "NUMBA_THREADING_LAYER": "omp",
    })

    import matplotlib
    matplotlib.use("Agg")  # belt-and-suspenders with MPLBACKEND set at module top
    import torch
    import app_lam  # importing does NOT launch gradio (that's under __main__)
    from lam.runners.infer.head_utils import prepare_motion_seqs, preprocess_image

    # parse_configs reads --blender_path off sys.argv; hand it a clean argv.
    sys.argv = ["colab_bake_flame.py", "--blender_path", args.blender_path]
    cfg, _ = app_lam.parse_configs()

    # TEETH: flip the config flag BEFORE building the model. Flows
    # ModelLAM.__init__ -> GS3DRenderer -> FlameHeadSubdivided(add_teeth=...). The
    # shipped configs/inference/lam-20k-8gpu.yaml has add_teeth:false. Unlike OAC,
    # this is the ONLY toggle needed — every exported artifact derives from the
    # same FlameHeadSubdivided tensors, so teeth stay consistent (no FBX desync).
    cfg.model.add_teeth = add_teeth
    print(f"cfg.model.add_teeth = {add_teeth} ({'TEETH' if add_teeth else 'no teeth'})")

    print("building model + flame tracking…")
    lam = app_lam._build_model(cfg)
    lam.to("cuda").eval()

    from tools.flame_tracking_single_image import FlameTrackingSingleImage
    flametracking = FlameTrackingSingleImage(
        output_dir="output/tracking",
        alignment_model_path="./model_zoo/flame_tracking_models/68_keypoints_model.pkl",
        vgghead_model_path="./model_zoo/flame_tracking_models/vgghead/vgg_heads_l.trcd",
        human_matting_path="./model_zoo/flame_tracking_models/matting/stylematte_synth.pt",
        facebox_model_path="./model_zoo/flame_tracking_models/FaceBoxesV2.pth",
        detect_iris_landmarks=False,
    )

    clip_dir = find_motion(args.motion)
    motion_seqs_dir = os.path.join(clip_dir, "flame_param")
    assert os.path.isdir(motion_seqs_dir), f"missing flame_param dir: {motion_seqs_dir}"
    flame_params_src = find_flame_params_json(clip_dir, args.flame_params)
    base_iid = os.path.basename(args.image).split(".")[0]
    if args.tag.strip():
        safe = "".join(c if c.isalnum() or c in "-_" else "_" for c in args.tag.strip())
        base_iid = f"{base_iid}_{safe}"
    print(f"image={args.image}  iid={base_iid}  clip={clip_dir}")
    print(f"flame_params.json (driving clip; overwritten live in spike): {flame_params_src}")

    # --- flame tracking on the input image (identical to OAC runner) ----------
    tmp_dir = "output/_bake_tmp"
    os.makedirs(tmp_dir, exist_ok=True)
    image_raw = os.path.join(tmp_dir, "raw.png")
    from PIL import Image
    with Image.open(args.image).convert("RGB") as im:
        im.save(image_raw)

    assert flametracking.preprocess(image_raw) == 0, "flametracking preprocess failed"
    assert flametracking.optimize() == 0, "flametracking optimize failed"
    rc, output_dir = flametracking.export()
    assert rc == 0, "flametracking export failed"

    image_path = os.path.join(output_dir, "images/00000_00.png")
    mask_path = os.path.join(output_dir, "fg_masks/00000_00.png")

    aspect_standard = 1.0 / 1.0
    image, _, _, shape_param = preprocess_image(
        image_path, mask_path=mask_path, intr=None, pad_ratio=0, bg_color=1.0,
        max_tgt_size=None, aspect_standard=aspect_standard, enlarge_ratio=[1.0, 1.0],
        render_tgt_size=cfg.source_size, multiply=14, need_mask=True, get_shape_param=True,
    )

    # --- optional shape warp (applied to the fitted betas, BEFORE all consumers) ---
    # Identical to the OAC runner. Must run before prepare_motion_seqs/infer AND before
    # save_h5_info/write_arkit_morphs so the gaussians (offset.ply) and the FLAME mesh
    # (nature.obj/skin.glb + the ARKit morph bases, all built from shape_param) get the
    # same modified shape — otherwise they desync.
    if args.shape_edit.strip():
        edits = []
        for tok in args.shape_edit.split(","):
            if not tok.strip():
                continue
            dim_s, delta_s = tok.split(":")
            dim, delta = int(dim_s), float(delta_s)
            assert 0 <= dim < shape_param.shape[-1], f"shape dim {dim} out of range (0..{shape_param.shape[-1]-1})"
            shape_param[dim] += delta
            edits.append(f"dim{dim}{delta:+g}")
        print(f"shape-edit applied to fitted betas: {', '.join(edits)}")

    src = image_path.split("/")[-3]
    driven = motion_seqs_dir.split("/")[-2]
    motion_seq = prepare_motion_seqs(
        motion_seqs_dir, None, save_root=tmp_dir, fps=30, bg_color=1.0,
        aspect_standard=aspect_standard, enlarge_ratio=[1.0, 1, 0],
        render_image_res=cfg.render_size, multiply=16, need_mask=False,
        vis_motion=False, shape_param=shape_param, test_sample=False,
        cross_id=False, src_driven=[src, driven],
    )

    # --- inference → canonical gaussians (identical to OAC runner) ------------
    device, dtype = "cuda", torch.float32
    motion_seq["flame_params"]["betas"] = shape_param.unsqueeze(0)
    print("running LAM inference…")
    with torch.no_grad():
        res = lam.infer_single_view(
            image.unsqueeze(0).to(device, dtype), None, None,
            render_c2ws=motion_seq["render_c2ws"].to(device),
            render_intrs=motion_seq["render_intrs"].to(device),
            render_bg_colors=motion_seq["render_bg_colors"].to(device),
            flame_params={k: v.to(device) for k, v in motion_seq["flame_params"].items()},
        )

    # === FLAME / h5 export (core_fn lines 283-289, sans the h5_rendering gate) ===
    # The Blender script's paths are HARDCODED to ./runtime_data — so we stage
    # there (cwd must be the LAM repo root), then assemble the final zip from it.
    h5_fd = "./runtime_data"
    if os.path.isdir(h5_fd):
        shutil.rmtree(h5_fd)  # avoid stale files from a previous bake
    os.makedirs(os.path.join(h5_fd, "bs"), exist_ok=True)

    # lbs_weight / bone_tree / nature / bs(PCA) — identity geometry, basis-independent
    print("save_h5_info → lbs_weight_20k.json, bone_tree.json, nature.obj, bs/expr0..99.obj …")
    lam.renderer.flame_model.save_h5_info(shape_param.unsqueeze(0).cuda(), fd=h5_fd)
    if args.arkit:
        print("⚠️  --arkit (EXPERIMENTAL): swapping PCA morphs → 52 ARKit blendshapes (clean blink)…")
        arkit_model = build_arkit_flame_model(cfg, add_teeth, args.arkit_bs)
        faces = lam.renderer.flame_model.faces_up.cpu().numpy()
        write_arkit_morphs(arkit_model, shape_param.unsqueeze(0).cuda(), faces, fd=h5_fd)

    print("save_ply → offset.ply …")
    res["cano_gs_lst"][0].save_ply(os.path.join(h5_fd, "offset.ply"), rgb2sh=False, offset2xyz=True)

    # teeth diagnostic: nature.obj vertex count (informational; this path doesn't desync)
    try:
        nverts = sum(1 for ln in open(os.path.join(h5_fd, "nature.obj")) if ln.startswith("v "))
        nbs = len(glob(os.path.join(h5_fd, "bs", "*.obj")))
        basis = "ARKit-52" if args.arkit else "expr-PCA"
        print(f"[flame] nature.obj verts={nverts}  blendshapes={nbs} ({basis})  teeth={'ON' if add_teeth else 'off'}")
    except Exception as e:
        print(f"[flame] count diagnostic skipped: {e}")

    print("Blender generateGLBWithBlender_v2.py → skin.glb + vertex_order.json …")
    rc = os.system(f'"{args.blender_path}" --background --python {blender_script}')
    assert rc == 0, f"Blender GLB export failed (exit {rc}). Check Blender>=4.0 and runtime_data/ inputs."
    for f in ("skin.glb", "vertex_order.json"):
        p = os.path.join(h5_fd, f)
        assert os.path.exists(p), f"Blender step did not produce {p}"

    # --- assemble OUR zip: inner folder == zip-name, WITH a directory entry ----
    # (create_zip_archive uses arcname h5_render_data/ and NO dir entry; our
    #  renderer discovers the folder via a DIRECTORY ENTRY or throws 'file fold is
    #  not found' — so we write the zip ourselves, like the OAC runner.)
    out_dir = "./output/flame_render"
    os.makedirs(out_dir, exist_ok=True)
    members = {
        "skin.glb": os.path.join(h5_fd, "skin.glb"),
        "flame_params.json": flame_params_src,
        "lbs_weight_20k.json": os.path.join(h5_fd, "lbs_weight_20k.json"),
        "bone_tree.json": os.path.join(h5_fd, "bone_tree.json"),
        "offset.ply": os.path.join(h5_fd, "offset.ply"),
        "vertex_order.json": os.path.join(h5_fd, "vertex_order.json"),
    }
    missing = [k for k, v in members.items() if not os.path.exists(v)]
    assert not missing, f"FLAME export incomplete, missing: {missing}"

    out_zip = os.path.join(out_dir, base_iid + ".zip")
    if os.path.exists(out_zip):
        os.remove(out_zip)
    with zipfile.ZipFile(out_zip, "w", zipfile.ZIP_DEFLATED) as z:
        di = zipfile.ZipInfo(base_iid + "/")
        di.external_attr = (0o40755 << 16) | 0x10  # unix dir bit + MS-DOS dir flag
        z.writestr(di, b"")
        for arcname, srcpath in members.items():
            z.write(srcpath, arcname=os.path.join(base_iid, arcname))

    print("\n✅ FLAME zip ready:", os.path.abspath(out_zip))
    print("   inner folder:", base_iid, "(with directory entry)")
    print("   contents:", ", ".join(members.keys()))
    print("   load it in the FLAME spike:  /flame-spike.html?avatar=<url to this zip>")
    print("   or compare v1 vs v2:         /compare.html?v1=<oac>&v2=<this flame zip>")


if __name__ == "__main__":
    main()
